name: meta
version: 2.0.0
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/meta
description: >-
 Annotations that developers can use to express the intentions that otherwise
 can't be deduced by statically analyzing the source code. These annotations
 are intended to be used by tools to provide a better user experience.
environment:
  sdk: ">=2.12.0 <3.0.0"
